### ISSUE TITLE
payment_icons v2.0

### ISSUE THREAD

**Issue by larouxn** [activemerchant/payment_icons#607]
Were we to release a v2.0 of `payment_icons` what changes would be nice to have?

- https://github.com/activemerchant/payment_icons/issues/506, so gem can be used in any Ruby application
- JavaScript package which can be imported as a module in any modern JavaScript application
- Rename all filenames and icon `name`s as all lowercase, no space, no hyphen, no underscore ([payment_icons.yml](https://github.com/activemerchant/payment_icons/blob/f12498edf6891084d64239493600e84c831244f0/db/payment_icons.yml))
  - This is a big breaking change but would prevent all future situations in which users are not sure how to name/call/access an icon.
  - If done, should add a test to CI to catch misnamed files/name definitions to prevent further cases. Can be done now too, i.e. "stop the bleeding" mentality.

With all of the above, anyone would be able to consistently use `payment_icons` and receive _just merge_ level upgrades.

**Comment by zbriscoe** [comment]
Curious, why standardize by removing all underscores rather than enforcing their usage in a consistent manner? Would make things much easier to read. Though you might be prioritizing simplicity here.

Rules on our side could be:
- if acronym: lowercase
- if camelcase: lowercase
- if space: replace with underscore
- if hyphen: replace with underscore

So some examples from what we have:
- `USDC` -> `usdc`
- `ViaBill` -> `viabill`
- `PrePay Solutions` -> `prepay_solution` rather than `prepaysolutions`
- `7-Eleven` -> `seven_eleven`

These rules would be applied based on what `label` is being supplied (as I'd assume that is generally aligned with how the payment method is branded and how it's documented.)

**Comment by larouxn** [comment]
> Curious, why standardize by removing all underscores rather than enforcing their usage in a consistent manner? Would make things much easier to read. Though you might be prioritizing simplicity here.

Definitely prioritizing simplicity here. The main inspiration for all lowercase, no space/hyphen/underscore is that our usage of these icons spans Ruby and JavaScript and both prefer differing string formatting. Ruby prefers `via_bill` while JavaScript prefers `viaBill`. Both however, lowest common denominator, are fine with `viabill`.

Effectively trying to reduce any chance of "off by 1" style name formatting issues causing icons to not show up across various surfaces. Surely numerical IDs or something would be even better but that would require more of an overhaul than consistent name formatting. Effectively trying to safeguard against my lack of understanding. 😅 

> Rules on our side could be:
> 
> * if acronym: lowercase
> * if camelcase: lowercase
> * if space: replace with underscore
> * if hyphen: replace with underscore

These sound good but we'd need to implement tests to enforce them, not impossible but something to consider, and "replace hyphen with underscore" works until we need to add the icon to a JavaScript module. 🤔
