### ISSUE TITLE
Sometimes old mobile pay icon is shown, sometimes new mobile pay  icon is shown

### ISSUE THREAD

**Issue by LouiseEH** [activemerchant/payment_icons#774]
Hi,

We have a payment app that uses the mobile pay icon, of which there has been several versions.
The challenge is that the most recent version of the icon is not always shown in the checkout c.f. the screenshots below.

![checkout-with-new-icon](https://user-images.githubusercontent.com/50172122/199462588-f6914a6f-6940-4aaf-b348-6ebc95a61719.jpg)

![checkout-with-old-icon](https://user-images.githubusercontent.com/50172122/199462599-61be7a01-1f6d-46c6-9ecf-b93cfe4bdf31.jpg)

Why is that? Do different shops have different versions of the icon library?
Seems odd though as the old icon was replaced by the most recent one on the 30th of March 2021 c.f. the changelog:
https://github.com/activemerchant/payment_icons/commits/master/app/assets/images/payment_icons/mobilepay.svg
https://github.com/activemerchant/payment_icons/commit/6ea3e5fb3acaa945253fe9c1b78530716725fb3d

**Comment by LouiseEH** [comment]
Any news here?

**Comment by Jacquesattaque** [comment]
Can you share links to the stores where you're seeing the old icon?

**Comment by LouiseEH** [comment]
Hi,
E.g. https://morfars.dk/ has the old, and e.g. https://ourunits.com/25148293169/checkouts/6b81d5d9009951aebf547194bf9fa4a0?previous_step=shipping_method&step=payment_method has the new.

**Comment by lunataoo** [comment]
It might be related to checkouts. [Checkout classic test example](https://ourunits.com/25148293169/checkouts/7cd88bd3f7bfeee7ebd0c40d3f43c34a?previous_step=shipping_method&step=payment_method) has the lighter icon; and[ C1 example cart ](https://morfars.dk/checkouts/c/97a43a748e62571b2acf6c9ae8c6ed1e/payment)has the darker icon.

For C1, I found this dark icon svg in the `checkout-web`(C1 front end) repo [here](https://github.com/Shopify/checkout-web/blob/master/packages/checkout-web-ui/src/components/PaymentIcon/images/mobilepay.svg). Maybe that's why it's overridden

**Comment by LouiseEH** [comment]
Hi @lunataoo 

Thank you for your reply @lunataoo.
Could you elaborate a bit, I am not quite sure what you mean?
If morfars.dk wanted to use the latest icon, what would they need to do? I would assume it should work out of the box, i.e. that Shopify always decides which checkout version and thus checkout icon version is used?

Thanks,
-Louise

**Comment by lunataoo** [comment]
@LouiseEH I'm not very familiar with how checkout renders the icons. If you could start a thread with the checkout front end team to look into this, in terms of why they load a static icon asset instead of the active merchant gem, that'll be great! 
I'm putting into the payments platform ATC triage board too, and we'll take a look at the backlog when our team has bandwidth.

**Comment by LouiseEH** [comment]
Ok thanks

**Comment by sylviafronczak** [comment]
@lunataoo Do you know if this issue is complete and can be closed? The linked issue is closed, so I think this one might be all set too, but I want to confirm.

**Comment by lunataoo** [comment]
@sylviafronczak Yes I think we can close this as it should be solved. TY!
