### ISSUE TITLE
Missing border on some icons

### ISSUE THREAD

**Issue by maximevaillancourt** [activemerchant/payment_icons#99]
## What's the issue?
The border is missing from some icons when rendered inline an HTML page (i.e. placing the `<svg>` tag directly in the document), whereas they appear when referenced in an `<img src='...'>` tag — see Apple Pay and Shopify Pay: 

**Inline (`<svg>` directly in the page):**
![image](https://user-images.githubusercontent.com/8457808/41248460-25c71ec8-6d7f-11e8-91f1-787052a9caad.png)

**In an `<img>` tag:**
![image](https://user-images.githubusercontent.com/8457808/41248494-3ccdf6be-6d7f-11e8-81d7-0c0a4975934b.png)

## Configuration
- macOS 10.13.4
- Google Chrome 66.0.3359.181 (Official Build) (64-bit)

**Comment by jonathanmoore** [comment]
The contributing guidelines does mention a "1 pixel wide solid grey border" but it doesn't specify a specific color.
https://github.com/jonathanmoore/payment_icons#user-content-contributing

**Comment by jonathanmoore** [comment]
Looking at the inconsistency a bit closer it seems to be coming from how the "1px grey border" is being added to the icon.

1. Some icons like Visa, PayPay and Master Card create the "1px grey border" with a solid shape fill set to black `#000` with 7% opacity.  
![image](https://user-images.githubusercontent.com/454095/41263475-45e26452-6d9c-11e8-8af3-5634de5a12be.png)
2. Other icons like Shopify Pay, Apple Pay, and Amazon Pay use a center position black `#000` with 7% opacity stroke.
![image](https://user-images.githubusercontent.com/454095/41263494-58333eba-6d9c-11e8-9438-03a15d0f6f93.png)

I can't speak from how specific browsers interpret strokes vs. stacked shapes, but I do know that any time you're placing shapes on half pixel values you will often run into rendering issues.  The second method of using center position strokes means that the icon's base shape is technically 37px by 23px in size positioned at `x: 0.5` and `y: 0.5`.  The half pixel positioning allows for the stroke to extend 0.5 px inside and outside the shape creating the final 38px by 24px size.

For consistency I would go with the first method since it avoids half pixel issues and it leaves less to interpret if the stroke should be inside, outside or center.

**Comment by jonathanmoore** [comment]
In addition to the stroke issues it seems like the same icons when used as inline SVGs do not preserve the solid white background.  
![image](https://user-images.githubusercontent.com/454095/41269678-6dfb9c6e-6dbb-11e8-8d78-0a8250e47953.png)

If you click to expand the images you can also see that the half pixel, center border icons appear slightly smaller
